//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x804a060
int32_t g2;

// ------------------------ Functions -------------------------

// From module:   /home/user/level10/level10.c
// Address range: 0x80486d4 - 0x804896c
// Line range:    11 - 73
int main(int argc, char ** argv) {
    int32_t v1 = __readgsdword(20); // 0x80486e7
    if (argc <= 2) {
        // 0x80486fc
        printf("%s file host\n\tsends file to host if you have access to it\n", *argv);
        exit(1);
        // UNREACHABLE
    }
    int32_t v2 = (int32_t)argv; // 0x804871f
    char * path = (char *)*(int32_t *)(v2 + 4); // 0x8048726
    int32_t chars_printed; // 0x80486d4
    if (access(path, R_OK) != 0) {
        // 0x8048940
        chars_printed = printf("You don't have access to %s\n", path);
    } else {
        char * cp = (char *)*(int32_t *)(v2 + 8); // 0x8048731
        printf("Connecting to %s:6969 .. ", cp);
        fflush((struct _IO_FILE *)g1);
        int32_t sock_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x804878f
        int32_t addr = 2; // bp-36, 0x80487ba
        inet_addr(cp);
        htons(0x1b39);
        if (connect(sock_fd, (struct sockaddr *)&addr, 16) == -1) {
            // 0x804880f
            printf("Unable to connect to host %s\n", cp);
            exit(1);
            // UNREACHABLE
        }
        // 0x8048830
        if (write(sock_fd, (int32_t *)".*( )*.\n", 8) == -1) {
            // 0x8048851
            printf("Unable to write banner to host %s\n", cp);
            exit(1);
            // UNREACHABLE
        }
        // 0x8048872
        printf("Connected!\nSending file .. ");
        fflush((struct _IO_FILE *)g1);
        int32_t fd = open(path, O_RDONLY); // 0x804889b
        if (fd == -1) {
            // 0x80488ab
            puts("Damn. Unable to open file");
            exit(1);
            // UNREACHABLE
        }
        // 0x80488c3
        int32_t buf; // bp-4132, 0x80486d4
        int32_t nbyte = read(fd, &buf, 0x1000); // 0x80488da
        if (nbyte == -1) {
            // 0x80488ea
            printf("Unable to read from file: %s\n", strerror(*__errno_location()));
            exit(1);
            // UNREACHABLE
        }
        // 0x8048916
        write(sock_fd, &buf, nbyte);
        chars_printed = puts("wrote file!");
    }
    int32_t result = chars_printed; // 0x8048963
    if (v1 != __readgsdword(20)) {
        // 0x8048965
        __stack_chk_fail();
        result = &g2;
    }
    // 0x804896a
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int * __errno_location(void);
// void __stack_chk_fail(void);
// int access(const char * name, int type);
// int connect(int fd, __CONST_SOCKADDR_ARG addr, socklen_t len);
// void exit(int status);
// int fflush(FILE * stream);
// uint16_t htons(uint16_t hostshort);
// in_addr_t inet_addr(const char * cp);
// int open(const char * file, int oflag, ...);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// ssize_t read(int fd, void * buf, size_t nbytes);
// int socket(int domain, int type, int protocol);
// char * strerror(int errnum);
// ssize_t write(int fd, const void * buf, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected language: C
// Detected functions: 1
