//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t afterSubstr(int32_t a1, int32_t a2);
int32_t function_80484a0(char * file, int32_t oflag, ...);
int32_t isLib(int32_t * a1, char * a2);
int32_t syscall_gets(int32_t * a1, int32_t a2, int32_t fd);
int32_t syscall_open(char * a1, int32_t a2);

// --------------------- Global Variables ---------------------

char (*g1)[5] = ".so\n"; // 0x804a030
struct _IO_FILE * g2 = NULL; // 0x804a040
struct _IO_FILE * g3 = NULL; // 0x804a060
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x80484a0 - 0x80484a6
int32_t function_80484a0(char * file, int32_t oflag, ...) {
    // 0x80484a0
    return open();
}

// Address range: 0x80485a4 - 0x80485d4
int32_t syscall_open(char * a1, int32_t a2) {
    // 0x80485a4
    return open();
}

// Address range: 0x80485d4 - 0x8048646
int32_t syscall_gets(int32_t * a1, int32_t a2, int32_t fd) {
    int32_t v1 = (int32_t)a1;
    int32_t v2 = 0; // 0x80485e3
    int32_t result = v2; // 0x804862c
    while (a2 - 1 > v2) {
        int32_t buf = v2 + v1; // 0x80485eb
        result = v2;
        if (read(fd, (int32_t *)buf, 1) != 1) {
            // break -> 0x8048631
            break;
        }
        // 0x804860a
        v2++;
        result = v2;
        if (*(char *)buf == 10) {
            // break -> 0x8048631
            break;
        }
        result = v2;
    }
    // 0x8048631
    *(char *)(result + v1) = 0;
    return result;
}

// Address range: 0x8048646 - 0x80486cb
int32_t afterSubstr(int32_t a1, int32_t a2) {
    int32_t v1 = a1; // 0x80486b1
    int32_t v2 = a1; // 0x80486b1
    int32_t v3 = 0; // 0x80486b1
    int32_t v4; // 0x8048646
    if (*(char *)a1 == 0) {
      lab_0x80486b6:
        // 0x80486b6
        return v3 != 0 ? v4 + v2 : 0;
    }
    int32_t v5 = 0; // 0x8048646
    int32_t v6 = 1; // 0x8048646
    char v7 = *(char *)(v5 + a2); // 0x8048698
    v2 = v1;
    v4 = v5;
    v3 = v6;
    if (v7 == 0) {
        return v3 != 0 ? v4 + v2 : 0;
    }
    char v8 = *(char *)(v5 + v1); // 0x804867a
    int32_t v9 = v7 == v8 ? v6 : 0;
    int32_t v10 = v5 + 1; // 0x8048688
    v5 = v10;
    v6 = v9;
    while (v9 == 1) {
        // 0x8048692
        v7 = *(char *)(v5 + a2);
        v2 = v1;
        v4 = v5;
        v3 = v6;
        if (v7 == 0) {
            return v3 != 0 ? v4 + v2 : 0;
        }
        // 0x804866b
        v8 = *(char *)(v5 + v1);
        v9 = v7 == v8 ? v6 : 0;
        v10 = v5 + 1;
        v5 = v10;
        v6 = v9;
    }
    // 0x80486a5
    v1++;
    while (*(char *)v1 != 0) {
        // 0x804868c
        v5 = 0;
        v6 = 1;
        v7 = *(char *)(v5 + a2);
        v2 = v1;
        v4 = v5;
        v3 = v6;
        if (v7 == 0) {
            return v3 != 0 ? v4 + v2 : 0;
        }
        // 0x804866b
        v8 = *(char *)(v5 + v1);
        v9 = v7 == v8 ? v6 : 0;
        v10 = v5 + 1;
        v5 = v10;
        v6 = v9;
        while (v9 == 1) {
            // 0x8048692
            v7 = *(char *)(v5 + a2);
            v2 = v1;
            v4 = v5;
            v3 = v6;
            if (v7 == 0) {
                return v3 != 0 ? v4 + v2 : 0;
            }
            // 0x804866b
            v8 = *(char *)(v5 + v1);
            v9 = v7 == v8 ? v6 : 0;
            v10 = v5 + 1;
            v5 = v10;
            v6 = v9;
        }
        // 0x80486a5
        v1++;
    }
    // 0x80486b6
    return v9 != 0 ? v10 + v1 : 0;
}

// Address range: 0x80486cb - 0x80487ce
int32_t isLib(int32_t * a1, char * a2) {
    int32_t v1 = afterSubstr((int32_t)a1, (int32_t)a2); // 0x80486de
    if (v1 == 0) {
        // 0x80487cc
        return 0;
    }
    char * v2 = (char *)v1; // 0x80486e3
    if (*v2 != 45) {
        // 0x80487cc
        return 0;
    }
    char * v3 = v2; // 0x80486fe
    int32_t v4 = 0;
    v3 = (char *)((int32_t)v3 + 1);
    char v5 = *v3; // 0x8048725
    while (v5 < 58) {
        // 0x8048722
        v4 = 1;
        v3 = (char *)((int32_t)v3 + 1);
        v5 = *v3;
    }
    // 0x8048736
    if (v4 != 0 != (v5 == 46)) {
        // 0x80487cc
        return 0;
    }
    int32_t v6 = 0;
    int32_t v7 = (int32_t)v3 + 1;
    char * v8 = (char *)v7;
    while (*v8 < 58) {
        // 0x8048765
        v6 = 1;
        v7 = (int32_t)v8 + 1;
        v8 = (char *)v7;
    }
    // 0x8048779
    if (v6 == 0) {
        // 0x80487cc
        return 0;
    }
    char v9 = g1[0]; // 0x80487c0
    if (v9 == 0) {
        // 0x80487cc
        return 1;
    }
    char v10 = v9; // 0x80487c0
    int32_t v11 = 0; // 0x80487b1
    int32_t result = 0; // 0x80487a8
    while (v10 == *(char *)(v11 + v7)) {
        // 0x80487b5
        v11++;
        v10 = *(char *)(v11 + (int32_t)g1);
        result = 1;
        if (v10 == 0) {
            // break -> 0x80487cc
            break;
        }
        result = 0;
    }
    // 0x80487cc
    return result;
}

// Address range: 0x80487ce - 0x8048a93
int main(int argc, char ** argv) {
    int32_t v1 = __readgsdword(20); // 0x80487e3
    int32_t items_written; // 0x80487ce
    int32_t v2; // 0x80487ce
    if (ptrace(0) >= 0) {
        // 0x8048840
        if (getenv("LD_PRELOAD") == NULL) {
            // 0x8048882
            if (function_80484a0("/etc/ld.so.preload", 0) < 1) {
                int32_t v3 = syscall_open("/proc/self/maps", 0); // 0x80488db
                if (v3 != -1) {
                    int32_t v4 = 0; // 0x80487ce
                    while (true) {
                        int32_t v5; // bp-276, 0x80487ce
                        int32_t v6 = syscall_gets(&v5, 256, v3); // 0x8048a68
                        items_written = v6;
                        if (v6 == 0) {
                            // break (via goto) -> 0x8048a77
                            goto lab_0x8048a77;
                        }
                        int32_t v7 = isLib(&v5, "libc"); // 0x8048930
                        // 0x8048a51
                        while (v4 != 0 && v7 == 0) {
                            // 0x8048951
                            if (isLib(&v5, "ld") != 0) {
                                if (argc != 2) {
                                    // 0x80489e4
                                    items_written = fwrite((int32_t *)"You need to provied only one arg.\n", 1, 34, g2);
                                    goto lab_0x8048a77;
                                } else {
                                    // 0x8048996
                                    v2 = -1;
                                    goto lab_0x8048996_2;
                                }
                            }
                            // 0x8048a0e
                            if (afterSubstr((int32_t)&v5, (int32_t)"00000000 00:00 0") == 0) {
                                // 0x8048a26
                                items_written = fwrite((int32_t *)"LD_PRELOAD detected through memory maps exit ..\n", 1, 48, g2);
                                goto lab_0x8048a77;
                            }
                            v6 = syscall_gets(&v5, 256, v3);
                            items_written = v6;
                            if (v6 == 0) {
                                // break (via goto) -> 0x8048a77
                                goto lab_0x8048a77;
                            }
                            // 0x8048921
                            v7 = isLib(&v5, "libc");
                        }
                        // 0x8048a51
                        v4 = v7 != 0;
                    }
                } else {
                    // 0x80488ef
                    fwrite((int32_t *)"/proc/self/maps is unaccessible, probably a LD_PRELOAD attempt exit..\n", 1, 70, g2);
                    items_written = 1;
                }
            } else {
                // 0x804889a
                fwrite((int32_t *)"Injection Linked lib detected exit..\n", 1, 37, g2);
                items_written = 1;
            }
        } else {
            // 0x8048850
            fwrite((int32_t *)"Injection Linked lib detected exit..\n", 1, 37, g2);
            items_written = 1;
        }
    } else {
        // 0x804882a
        puts("You should not reverse this");
        items_written = 1;
    }
    goto lab_0x8048a77;
  lab_0x8048a77:;
    int32_t result = items_written; // 0x8048a85
    if (v1 != __readgsdword(20)) {
        // 0x8048a87
        __stack_chk_fail();
        result = &g4;
    }
    // 0x8048a8c
    return result;
  lab_0x8048996_2:;
    int32_t v8 = v2 + 1; // 0x8048996
    int32_t v9 = *(int32_t *)((int32_t)argv + 4); // 0x80489a6
    int32_t v10 = -1; // 0x80489bd
    int32_t v11 = v9; // 0x80489bd
    goto lab_dec_label_pc_unknown;
  lab_dec_label_pc_unknown:;
    int32_t v12 = v10;
    int32_t v13 = 0; // 0x80489bd
    if (v12 == 0) {
        goto lab_dec_label_pc_unknown_2;
    } else {
        int32_t v14 = v11;
        int32_t v15 = v12 - 1; // 0x80489bd
        v10 = v15;
        bool v16; // 0x80487ce
        v11 = v14 + (v16 ? -1 : 1);
        v13 = v15;
        if (*(char *)v14 == 0) {
            goto lab_dec_label_pc_unknown_2;
        } else {
            goto lab_dec_label_pc_unknown;
        }
    }
  lab_dec_label_pc_unknown_2:
    if (v8 < -2 - v13) {
        // 0x8048975
        putchar(v8 + (int32_t)*(char *)(v9 + v8));
        v2 = v8;
        goto lab_0x8048996_2;
    } else {
        // 0x80489ca
        items_written = fputc(10, g3);
        goto lab_0x8048a77;
    }
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// int fputc(int c, FILE * stream);
// size_t fwrite(const void * restrict ptr, size_t size, size_t n, FILE * restrict s);
// char * getenv(const char * name);
// long int ptrace(enum __ptracerequest __request, ...);
// int putchar(int c);
// int puts(const char * s);

// ------------------ System-Call Functions -------------------

// int32_t open(void);
// ssize_t read(int fd, void * buf, size_t nbytes);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 6
