//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// From module:   /home/user/level08/level08.c
// Address range: 0x8048554 - 0x80486a4
// Line range:    8 - 37
int main() {
    char buf[1024]; // bp-1044, 0x8048554
    int32_t v1 = __readgsdword(20); // 0x804856e
    if (argc == 1) {
        // 0x8048583
        printf("%s [file to read]\n", *argv);
        exit(1);
        // UNREACHABLE
    }
    int32_t * str = (int32_t *)((int32_t)argv + 4); // 0x80485ad
    char * substr_pos = strstr((char *)*str, "token"); // 0x80485ba
    char * path = (char *)*str;
    if (substr_pos != NULL) {
        // 0x80485c3
        printf("You may not access '%s'\n", path);
        exit(1);
        // UNREACHABLE
    }
    int32_t fd = open(path, O_RDONLY); // 0x80485fd
    if (fd == -1) {
        // 0x804860d
        err(1, "Unable to open %s", (char *)*str);
    }
    int32_t nbyte = read(fd, (int32_t *)&buf, 1024); // 0x8048645
    if (nbyte == -1) {
        // 0x8048655
        err(1, "Unable to read fd %d", fd);
    }
    int32_t result = write(1, (int32_t *)&buf, nbyte); // 0x804869b
    if (v1 != __readgsdword(20)) {
        // 0x804869d
        __stack_chk_fail();
        result = &g1;
    }
    // 0x80486a2
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// void err(int status, const char * format, ...);
// void exit(int status);
// int open(const char * file, int oflag, ...);
// int printf(const char * restrict format, ...);
// ssize_t read(int fd, void * buf, size_t nbytes);
// char * strstr(char * haystack, const char * needle);
// ssize_t write(int fd, const void * buf, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected language: C
// Detected functions: 1
