//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Functions -------------------------

// From module:   /home/user/level03/level03.c
// Address range: 0x80484a4 - 0x8048505
// Line range:    7 - 18
int main() {
    int32_t v1 = getegid(); // 0x80484ad
    int32_t v2 = geteuid(); // 0x80484b6
    setresgid(v1, v1, v1);
    setresuid(v2, v2, v2);
    return system("/usr/bin/env echo Exploit me");
}

// --------------- Dynamically Linked Functions ---------------

// __gid_t getegid(void);
// __uid_t geteuid(void);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);
// int setresuid(__uid_t ruid, __uid_t euid, __uid_t suid);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected language: C
// Detected functions: 1
