//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int32_t ft_des(char * str);

// ------------------------ Functions -------------------------

// Address range: 0x8048474 - 0x804858c
int32_t ft_des(char * str) {
    int32_t result = (int32_t)strdup(str);
    uint32_t v1 = 0;
    int32_t v2 = 0;
    int32_t v3 = result; // 0x8048571
    int32_t v4 = -1;
    int32_t v5 = 0; // 0x8048571
    int32_t v6; // 0x8048474
    bool v7; // 0x8048474
    int32_t v8; // 0x8048571
    while (v4 != 0) {
        v6 = v3;
        v8 = v4 - 1;
        v3 = v6 + (v7 ? -1 : 1);
        v5 = v8;
        if (*(char *)v6 == 0) {
            // break -> 
            break;
        }
        v4 = v8;
        v5 = 0;
    }
    while (-2 - v5 > v1) {
        int32_t v9 = v2 != 6 ? v2 : 0;
        char * v10 = (char *)(v9 + (int32_t)"0123456");
        char v11 = *v10;
        if (v1 % 2 == 0) {
            if (v11 > 0) {
                char * v12 = (char *)(v1 + result); // 0x804851a
                char v13 = *v12;
                for (int32_t i = 0; i < (int32_t)*v10; i++) {
                    char v14 = v13 - 1; // 0x804851d
                    v13 = v14 != 31 ? v14 : 126;
                    *v12 = v13;
                }
            }
        } else {
            if (v11 > 0) {
                char * v15 = (char *)(v1 + result); // 0x80484c4
                char v16 = *v15;
                for (int32_t i = 0; i < (int32_t)*v10; i++) {
                    char v17 = v16 + 1; // 0x80484c7
                    v16 = v17 != 127 ? v17 : 32;
                    *v15 = v16;
                }
            }
        }
        // 0x8048553
        v1++;
        v2 = v9 + 1;
        v3 = result;
        v4 = -1;
        v5 = 0;
        while (v4 != 0) {
            v6 = v3;
            v8 = v4 - 1;
            v3 = v6 + (v7 ? -1 : 1);
            v5 = v8;
            if (*(char *)v6 == 0) {
                // break -> 
                break;
            }
            v4 = v8;
            v5 = 0;
        }
    }
    // 0x8048583
    return result;
}

// Address range: 0x804858c - 0x80485ea
int main(int argc, char ** argv) {
    // 0x804858c
    if (getuid() == 0x1092) {
        // 0x80485cb
        return printf("your token is %s\n", (char *)ft_des("boe]!ai0FB@.:|L6l@A?>qJ}I"));
    }
    // 0x80485a1
    printf("UID %d started us but we we expect %d\n", getuid(), 0x1092);
    exit(1);
    // UNREACHABLE
}

// --------------- Dynamically Linked Functions ---------------

// void exit(int status);
// __uid_t getuid(void);
// int printf(const char * restrict format, ...);
// char * strdup(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 2

