//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// --------------------- Global Variables ---------------------

char * g1; // 0x80487d4

// ------------------------ Functions -------------------------

// Address range: 0x8048450 - 0x8048527
int main(int argc, char ** argv) {
    char * envp[1]; // 0x8048514
    char * exec_argv[1]; // 0x8048514
    int32_t v1 = (int32_t)argv;
    char * v2 = strdup((char *)&g1); // 0x8048472
    char * v3 = strdup((char *)&g1); // 0x8048480
    int32_t * str = (int32_t *)(v1 + 4); // 0x8048488
    if (*str != 0) {
        // 0x8048490
        free((int32_t *)v2);
        strdup((char *)*str);
        int32_t * str2 = (int32_t *)(v1 + 8); // 0x80484a5
        if (*str2 != 0) {
            // 0x80484ad
            free((int32_t *)v3);
            strdup((char *)*str2);
        }
    }
    int32_t v4 = getegid(); // 0x80484c4
    int32_t v5 = geteuid(); // 0x80484cc
    setresgid(v4, v4, v4);
    setresuid(v5, v5, v5);
    char * v6 = "/usr/bin/php"; // bp-52, 0x80484ff
    exec_argv[0] = (char *)&v6;
    int32_t v7; // 0x8048450
    envp[0] = (char *)v7;
    execve("/usr/bin/php", exec_argv, envp);
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int execve(const char * path, char * const argv[], char * const envp[]);
// void free(void * ptr);
// __gid_t getegid(void);
// __uid_t geteuid(void);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);
// int setresuid(__uid_t ruid, __uid_t euid, __uid_t suid);
// char * strdup(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 1
